#:schema https://docs.jj-vcs.dev/latest/config-schema.json
#:tombi toml-version = "v1.1.0"

[user]
name = "ninjack-dev"
email = "84806918+ninjack-dev@users.noreply.github.com"

[aliases]
update-branches = {
  doc = "Rebase branches off of the trunk onto the last commit",
  definition = ["rebase", "--source", "roots(trunk().. ~ ::@-)", "--onto", "@-", "--skip-emptied"],
  }
