font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 1

scrollbar_interactive no

# https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#solution-1
env LESSUTFCHARDEF=e000-f8ff:p,f0001-fffff:p
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

window_padding_width 5 8

placement_strategy center

confirm_os_window_close 0

allow_remote_control yes
listen_on unix:@kitty
env PATH=${XDG_CONFIG_HOME}/kitty/wrappers:${PATH}
# TODO: Pull this into a global environment manager at some point
env SHELL=zsh

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

shell_integration enabled
