#!/bin/sh
_SHELL="$(whereis nu | awk 'NR == 1 { printf "%s", $3 }')"
[ -z "$_SHELL" ] && { printf 'Nushell not found in PATH' 2>&1; exit 1; }
exec kitten run-shell --shell="$_SHELL $($(whereis printf | awk '{print $NF}') ' %q' "$@")"
