#!/bin/sh
_SHELL="$(whereis zsh | awk 'NR == 1 { printf "%s", $3 }')"
[ -z "$_SHELL" ] && { printf 'Zsh not found in PATH\n' 2>&1; exit 1; }
exec kitten run-shell --shell="$_SHELL $($(whereis printf | awk '{print $NF}') ' %q' "$@")"
